### ISSUE TITLE
Detection is very slow instead of around ~30 fps

### ISSUE THREAD

**Issue by rarenicks** [surendramaran/YOLOv8-TfLite-Object-Detector#12]
The app is slow in detection even when getting decent fps (30~40 fps) on GPU, maybe some optimisation on camera frame reading or rendering, skipping the use of buffer frames and directly using latest frames may improve performance.

**Comment by surendramaran** [comment]
It is skipping the images and taking only the latest image to run.

imageAnalyzer = ImageAnalysis.Builder()
    .setTargetAspectRatio(AspectRatio.RATIO_4_3)
    .setBackpressureStrategy(ImageAnalysis.STRATEGY_KEEP_ONLY_LATEST)
    .setTargetRotation(binding.viewFinder.display.rotation)
    .setOutputImageFormat(ImageAnalysis.OUTPUT_IMAGE_FORMAT_RGBA_8888)
    .build()


this

.setBackpressureStrategy(ImageAnalysis.STRATEGY_KEEP_ONLY_LATEST)


take care of all of the skipping.

The fps depends on devices, Android has limited resources so it runs slow.
