### ISSUE TITLE
i have an issue with the app crashes.

### ISSUE THREAD

**Issue by lerapela** [surendramaran/YOLOv8-TfLite-Object-Detector#18]
The input of my TensorFlow lite model is 1 * 3 * 640 * 640 and the  output is 1 * 37 * 8400. at first it was crashing immediately and i implemented this dependency "implementation ("org.tensorflow:tensorflow-lite-select-tf-ops:2.10.0")" . and now it takes around 10 seconds to crash. i need help...

**Comment by surendramaran** [comment]
I'll take a look, share the model [surendramaran8@gmail.com](mailto:user@example.com)

**Comment by surendramaran** [comment]
The issue is resolved. It occurred because of not properly exporting the model into tflite.

**Comment by lerapela** [comment]
Can I have the code to properly export model from pytorch to tensorflowlite.

Thank again sir for your help

**Comment by surendramaran** [comment]
I used terminal to export.
yolo export model=yolov8n.pt format=tflite imgsz=1280 int8=false

**Comment by lerapela** [comment]
Thanks, I'll check it out.
