### ISSUE TITLE
Inference Time slower than Ultralytics

### ISSUE THREAD

**Issue by quocnhat** [surendramaran/YOLOv8-TfLite-Object-Detector#21]
Hi, I've tested yolov8s_float32.tflite model on both Ultralytics hub and yours, But The speed from Ultralytics is almost 4x. 
Does that Gap come from C++ ( Ultralytics) and Koltin (yours)?
Can you explain why? Thank you.

**Comment by surendramaran** [comment]
Kotlin and C++ both are comparatively faster. There are no such difference in speed if we talk about languages. Android generally have less resources and we are doing live detection with camera, so probably camera is also consuming some amount of CPU. Anyways there could be other reasons but language are not definitely not the one. And ultralytics is in python probably. OpenCv is C++. I think so.

**Comment by quocnhat** [comment]
Thank you for your information, Ultralytics android hub does not public source code yet, So we can not specify the correct answer.
btw, thank you so much for your great open-source code.
