### ISSUE TITLE
try to use gpu or nnapi, but it didn't work

### ISSUE THREAD

**Issue by visonpon** [surendramaran/YOLOv8-TfLite-Object-Detector#4]
Hi， @surendramaran ，thanks for sharing this wonderful work. I tried to set like below in `Detector.kt`:
```
val options = Interpreter.Options()
options.numThreads = 4
//options.setNumThreads(4)
options.setUseNNAPI(true)
interpreter = Interpreter(model, options)
```
but has no speed up.what's more, when i try to use ` options.addDelegate(GpuDelegate())` ,the app crashed.
Hope you can give some advice, thanks~
(btw, hope you can provide the environment setup)

**Comment by philipmortimer** [comment]
May be very much a case of different devices different results etc, but I found that I was able to get NNAPI working on my low end google pixel device which led to a pretty substantial boost to inference time. Here's the code I used, taken straight from the TFLite website (https://www.tensorflow.org/lite/android/delegates/nnapi):

`

        val model = FileUtil.loadMappedFile(context, modelPath)

        val options = Interpreter.Options()
        var nnApiDelegate: NnApiDelegate? = null
        // Initialize interpreter with NNAPI delegate for Android Pie or above
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
            nnApiDelegate = NnApiDelegate()
            options.addDelegate(nnApiDelegate)
        } else {options.numThreads = 4}

        interpreter = Interpreter(model, options)

`

**Comment by philipmortimer** [comment]
Hi just a little follow up, I've been trying to do something similar to you I think. Out of the box on a Google Pixel 4, model inference (i.e. just "interpreter?.run(imageBuffer, output.buffer)") took about 260ms. Using the nnApi delegate as above reduces the inference time to about 115ms. Using the GPU delegate reduces runtime to 50ms. Combining the two delegates seems to make no difference on my device. I will explore quantization but a brief set of experiments indicate minimal to no speed up (though this does need further experimentation).

In your post you mention the app crashes when adding the GPU delegate the same happened to me. My code is as follows (for adding the GPU delegate):
`

       val options = Interpreter.Options()
        val compatList = CompatibilityList()
        if(compatList.isDelegateSupportedOnThisDevice){
            // if the device has a supported GPU, add the GPU delegate
            val delegateOptions = compatList.bestOptionsForThisDevice
            options.addDelegate(GpuDelegate(delegateOptions))
        }
        interpreter = Interpreter(model, options)

`

When following the default tflite guide, my code crashes. I had to set up different imports and alter my android manifest file. My imports are:
import org.tensorflow.lite.gpu.CompatibilityList
import org.tensorflow.lite.gpu.GpuDelegate

I had to link the openCL library in my android manifest to allow it to be used:

<application>
...
        <uses-native-library
            android:name="libOpenCL.so"
            android:required="false"/>

        <uses-native-library
            android:name="libOpenCL-pixel.so"
            android:required="false" />
</application>

And these were my tensorflow versions in the gradle build file:

    implementation("org.tensorflow:tensorflow-lite-gpu-api:2.12.0")
    implementation ("org.tensorflow:tensorflow-lite-gpu-delegate-plugin:0.4.4")
    implementation("org.tensorflow:tensorflow-lite:2.14.0")
    implementation("org.tensorflow:tensorflow-lite-support:0.4.4")

    implementation("org.tensorflow:tensorflow-lite-api:2.14.0")
    implementation("org.tensorflow:tensorflow-lite-gpu:2.10.0")


Hope this may be useful to you! P.s. the error message I was getting was something like:
"java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: Can not open OpenCL library on this device - dlopen failed: library "libOpenCL.so" not found tflite android gpu delegate intepreter" etc.

**Comment by christophemenager** [comment]
Thanks @philipmortimer , on my side I had to add
```
 <uses-native-library
        android:name="libOpenCL.so"
        android:required="false"/>
    <uses-native-library
        android:name="libOpenCL-pixel.so"
        android:required="false" />
```

Model inference time dropped from 150ms down to 50ms after this !

**Comment by rarenicks** [comment]
This functionality is not tested and merged into main.

**Comment by surendramaran** [comment]
Working on it, for now I revert the functionality

**Comment by surendramaran** [comment]
@christophemenager can you share more insight on why these tag are essential?

**Comment by christophemenager** [comment]
@rarenicks just to clarify:
- What's your problem? Can you paste the error here?
- What do you mean by no tested, how can you tell it has not been tested?

@surendramaran I don't remember exactly the error, but I had an error at run time (the build was successful) on my One plus. 
I guess it depends on the device you use, but I have tested this build on more than 10 real android devices and I had no error.

**Comment by surendramaran** [comment]
The error was unknown, I reverted and tried again and it worked. I already pushed new code. I wanted to learn about that those uses-native-library tags. Why they are essential?
