### ISSUE TITLE
Optimize inference time

### ISSUE THREAD

**Issue by yogiant333** [surendramaran/YOLOv8-TfLite-Object-Detector#6]
Hi, thank you for your work. Give me a lot of help.
 I noticed there seems to be room for optimization in the inference time. Inference only took 25ms, but it took 281ms from input data to output result. I wonder if there's a better approach.
``` 
fun detect(frame: Bitmap) {
        if (tensorWidth == 0) return
        if (tensorHeight == 0) return
        if (numChannel == 0) return
        if (numElements == 0) return

        var inferenceTime = SystemClock.uptimeMillis()

        val resizedBitmap = Bitmap.createScaledBitmap(frame, tensorWidth, tensorHeight, false)
        
        val tensorImage = TensorImage(DataType.FLOAT32)
        tensorImage.load(resizedBitmap)
        val processedImage = imageProcessor.process(tensorImage)
        val imageBuffer = processedImage.buffer

        val output =
            TensorBuffer.createFixedSize(intArrayOf(1, numChannel, numElements), OUTPUT_IMAGE_TYPE)

        var start = System.currentTimeMillis()
        println("start inference")
        interpreter.run(imageBuffer, output.buffer)
        println("inference cost：${System.currentTimeMillis() - start}ms")

        val bestBoxes = bestBox(output.floatArray)
        if (bestBoxes == null) {
            detectorListener.onEmptyDetect()
            return
        }

        inferenceTime = SystemClock.uptimeMillis() - inferenceTime
        detectorListener.onDetect(bestBoxes, inferenceTime)
    }
```

```
override fun onDetect(boundingBoxes: List<BoundingBox>, inferenceTime: Long) {
        println("boundingBoxes: $boundingBoxes inferenceTime: $inferenceTime")
        runOnUiThread {
            binding.inferenceTime.text = "${inferenceTime}ms"
            binding.overlay.apply {
                setResults(boundingBoxes)
                invalidate()
            }
        }
    }
```
```
2024-03-16 22:56:19.929 11118-11118 System.out              com.surendramaran.yolov8tflite       I  start inference
2024-03-16 22:56:19.955 11118-11118 System.out              com.surendramaran.yolov8tflite       I  inference cost：25ms
2024-03-16 22:56:20.083 11118-11118 System.out              com.surendramaran.yolov8tflite       I  boundingBoxes: [BoundingBox(x1=0.61886597, y1=0.34298706, x2=0.7121887, y2=0.46072388, cx=0.66552734, cy=0.40185547, w=0.093322754, h=0.11773682, cnf=0.83203125, cls=1, clsName=helmet)] inferenceTime: 281
```

**Comment by surendramaran** [comment]
It is very interesting observation, when I tried to check times. I got 110ms for interface run, 60ms for NMS, and 1ms for displaying. The NMS process is important as well. Maybe any different NMS approach can reduce time.

**Comment by philipmortimer** [comment]
As mentioned the actual YOLO inference can be quick (especially by using GPU delegate). I have taken a number of steps to speed up the overall processing pipeline depending on your ultimate use case (e.g. avoid unnecessary scaling, rotation and buffer creation). However, you can also make completely free optimisations which do dramatically speed up runtime.
Specifically, the bestBox function is unnecessarily slow.
To find the predicted class and associated confidence the code does this:


`            
            val confidences = (4 until numChannel).map { array[c + numElements * it] }
            val cnf = confidences.max()
`

This is really nice and readable but leads to slow performance as for each of the 8400 possible regions (in the base yolo model) it is creating a datastructure storing the confidence predictions for each class (80 elements for the base model). So essentially you are creating an array like datastructure of 80 elements 8400 times. I have replaced this code with something like this:

`

            var maxConf = -1.0f
            var maxIdx = -1
            var j = 4
            var arrayIdx = c + numElements * j
            while (j < numChannel){
                if (array[arrayIdx] > maxConf) {
                    maxConf = array[arrayIdx]
                    maxIdx = j - 4
                }
                j++
                arrayIdx += numElements
            }

`
It's just a simple case of using the maxConf and maxIdx variable and replacing the correct values in the corresponding if statement. The code is less readable but it reduces my NMS region of code from 120ms to 3ms. Quite the speedup.

**Comment by surendramaran** [comment]
I'll give it a try

**Comment by surendramaran** [comment]
Yeah, you were right, I was able to reduce time with big improvement. Thanks!!
