### ISSUE TITLE
Yolov5

### ISSUE THREAD

**Issue by DuckonFire** [surendramaran/YOLOv8-TfLite-Object-Detector#9]
Can this git work for yolov5? Ive try to run my .tflite (yolov5) but the app crash.
Does it have corelation with the float? Bcs yolov5 use float 16 and this use float32. If yes, how to make this app compatible with float 16? Bcs i cant find solution to make yolov5 float 32.

**Comment by surendramaran** [comment]
No it won't work. There are repos for yolov5. Which you can use. I've not tried them though.
